setwd("C:/Users/Pavan Kumar/Desktop/DWBI/WorkingDirectory/")
library(dplyr)
library(tidyr)
library(xml2)
library(rvest)
library(sqldf)

Co2_Oil <- read.csv("C:/Users/Pavan Kumar/Desktop/DWBI/Energy/Oil_CO2.csv")
Co2_Oil[1,1] <- "Year"
Co2_Oil <- Co2_Oil[,c(1,4,9,12,20,29,37,42,43,44,54,61,71,77,93,94,95,99,101,103,106,121,129,141,143,146,149,159,160,164,165,174,184,185,186,191,194,197,203,208,209,210,211,213,215)]
colnames(Co2_Oil) <- c("Year","Algeria",
                       "Argentina",
                       "Australia",
                       "Belgium",
                       "Brazil",
                       "Canada",
                       "Chile",
                       "China",
                       "Colombia",
                       "Czech Republic",
                       "Egypt",
                       "France",
                       "Germany",
                       "India",
                       "Indonesia",
                       "Iran",
                       "Italy",
                       "Japan",
                       "Kazakhstan",
                       "Kuwait",
                       "Malaysia",
                       "Mexico",
                       "Netherlands",
                       "New Zealand",
                       "Nigeria",
                       "Norway",
                       "Poland",
                       "Portugal",
                       "Romania",
                       "Russian Federation",
                       "Saudi Arabia",
                       "South Africa",
                       "South Korea",
                       "Spain",
                       "Sweden",
                       "Taiwan",
                       "Thailand",
                       "Turkey",
                       "Ukraine",
                       "United Arab Emirates",
                       "United Kingdom",
                       "United States",
                       "Uzbekistan",
                       "Venezuela")
Co2_Oil <- Co2_Oil[-1:-3,]
Co2_Oil <- Co2_Oil %>% gather (Country,Co2_Emission_in_mtCo2,Algeria,
                               Argentina,
                               Australia,
                               Belgium,
                               Brazil,
                               Canada,
                               Chile,
                               China,
                               Colombia,
                               `Czech Republic`,
                               Egypt,
                               France,
                               Germany,
                               India,
                               Indonesia,
                               Iran,
                               Italy,
                               Japan,
                               Kazakhstan,
                               Kuwait,
                               Malaysia,
                               Mexico,
                               Netherlands,
                               `New Zealand`,
                               Nigeria,
                               Norway,
                               Poland,
                               Portugal,
                               Romania,
                               `Russian Federation`,
                               `Saudi Arabia`,
                               `South Africa`,
                               `South Korea`,
                               Spain,
                               Sweden,
                               Taiwan,
                               Thailand,
                               Turkey,
                               Ukraine,
                               `United Arab Emirates`,
                               `United Kingdom`,
                               `United States`,
                               Uzbekistan,
                               Venezuela
                               ,-Year)

rownames(Co2_Oil) <- c(1:nrow(Co2_Oil))
Co2_Oil$Region <-  ifelse(Co2_Oil$Country == 'Canada',"North America",
                          ifelse(Co2_Oil$Country == 'United States',"North America",                                                           
                                 ifelse(Co2_Oil$Country == 'Argentina',"South and Central America",
                                        ifelse(Co2_Oil$Country == 'Brazil',"South and Central America",
                                               ifelse(Co2_Oil$Country == 'Chile',"South and Central America",
                                                      ifelse(Co2_Oil$Country == 'Colombia',"South and Central America",
                                                             ifelse(Co2_Oil$Country == 'Mexico',"South and Central America",
                                                                    ifelse(Co2_Oil$Country == 'Venezuela',"South and Central America",
                                                                           ifelse(Co2_Oil$Country == 'China',"Asia Pacific",
                                                                                  ifelse(Co2_Oil$Country == 'India',"Asia Pacific",
                                                                                         ifelse(Co2_Oil$Country == 'Indonesia',"Asia Pacific",
                                                                                                ifelse(Co2_Oil$Country == 'Japan',"Asia Pacific",
                                                                                                       ifelse(Co2_Oil$Country == 'Malaysia',"Asia Pacific",
                                                                                                              ifelse(Co2_Oil$Country == 'South Korea',"Asia Pacific",
                                                                                                                     ifelse(Co2_Oil$Country == 'Taiwan',"Asia Pacific",
                                                                                                                            ifelse(Co2_Oil$Country == 'Thailand',"Asia Pacific",                                                 
                                                                                                                                   ifelse(Co2_Oil$Country == 'Australia',"Asia Pacific",
                                                                                                                                          ifelse(Co2_Oil$Country == 'New Zealand',"Asia Pacific",
                                                                                                                                                 ifelse(Co2_Oil$Country == 'South Africa',"Middle East and Africa",
                                                                                                                                                        ifelse(Co2_Oil$Country == 'Algeria',"Middle East and Africa",
                                                                                                                                                               ifelse(Co2_Oil$Country == 'Egypt',"Middle East and Africa",
                                                                                                                                                                      ifelse(Co2_Oil$Country == 'Nigeria',"Middle East and Africa",
                                                                                                                                                                             ifelse(Co2_Oil$Country == 'Iran',"Middle East and Africa",
                                                                                                                                                                                    ifelse(Co2_Oil$Country == 'Kuwait',"Middle East and Africa",
                                                                                                                                                                                           ifelse(Co2_Oil$Country == 'Saudi Arabia',"Middle East and Africa", 
                                                                                                                                                                                                  ifelse(Co2_Oil$Country == 'United Arab Emirates',"Middle East and Africa","Europe and CIS"))))))))))))))))))))))))))
Co2_Oil <- Co2_Oil[c(1,4,2,3)]
write.csv(Co2_Oil,file = "Co2_Oil.csv",row.names = FALSE)



#---------Gas-----------



Co2_Gas <- read.csv("C:/Users/Pavan Kumar/Desktop/DWBI/Energy/Gas_CO2.csv")
Co2_Gas[1,1] <- "Year"
Co2_Gas <- Co2_Gas[,c(1,4,9,12,20,29,37,42,43,44,54,61,71,77,93,94,95,99,101,103,106,121,129,141,143,146,149,159,160,164,165,174,184,185,186,191,194,197,203,208,209,210,211,213,215)]
colnames(Co2_Gas) <- c("Year","Algeria",
                       "Argentina",
                       "Australia",
                       "Belgium",
                       "Brazil",
                       "Canada",
                       "Chile",
                       "China",
                       "Colombia",
                       "Czech Republic",
                       "Egypt",
                       "France",
                       "Germany",
                       "India",
                       "Indonesia",
                       "Iran",
                       "Italy",
                       "Japan",
                       "Kazakhstan",
                       "Kuwait",
                       "Malaysia",
                       "Mexico",
                       "Netherlands",
                       "New Zealand",
                       "Nigeria",
                       "Norway",
                       "Poland",
                       "Portugal",
                       "Romania",
                       "Russian Federation",
                       "Saudi Arabia",
                       "South Africa",
                       "South Korea",
                       "Spain",
                       "Sweden",
                       "Taiwan",
                       "Thailand",
                       "Turkey",
                       "Ukraine",
                       "United Arab Emirates",
                       "United Kingdom",
                       "United States",
                       "Uzbekistan",
                       "Venezuela")
Co2_Gas <- Co2_Gas[-1:-3,]
Co2_Gas <- Co2_Gas %>% gather (Country,Co2_Emission_in_mtCo2,Algeria,
                               Argentina,
                               Australia,
                               Belgium,
                               Brazil,
                               Canada,
                               Chile,
                               China,
                               Colombia,
                               `Czech Republic`,
                               Egypt,
                               France,
                               Germany,
                               India,
                               Indonesia,
                               Iran,
                               Italy,
                               Japan,
                               Kazakhstan,
                               Kuwait,
                               Malaysia,
                               Mexico,
                               Netherlands,
                               `New Zealand`,
                               Nigeria,
                               Norway,
                               Poland,
                               Portugal,
                               Romania,
                               `Russian Federation`,
                               `Saudi Arabia`,
                               `South Africa`,
                               `South Korea`,
                               Spain,
                               Sweden,
                               Taiwan,
                               Thailand,
                               Turkey,
                               Ukraine,
                               `United Arab Emirates`,
                               `United Kingdom`,
                               `United States`,
                               Uzbekistan,
                               Venezuela,-Year)

rownames(Co2_Gas) <- c(1:nrow(Co2_Gas))
Co2_Gas$Region <-  ifelse(Co2_Gas$Country == 'Canada',"North America",
                          ifelse(Co2_Gas$Country == 'United States',"North America",                                                           
                                 ifelse(Co2_Gas$Country == 'Argentina',"South and Central America",
                                        ifelse(Co2_Gas$Country == 'Brazil',"South and Central America",
                                               ifelse(Co2_Gas$Country == 'Chile',"South and Central America",
                                                      ifelse(Co2_Gas$Country == 'Colombia',"South and Central America",
                                                             ifelse(Co2_Gas$Country == 'Mexico',"South and Central America",
                                                                    ifelse(Co2_Gas$Country == 'Venezuela',"South and Central America",
                                                                           ifelse(Co2_Gas$Country == 'China',"Asia Pacific",
                                                                                  ifelse(Co2_Gas$Country == 'India',"Asia Pacific",
                                                                                         ifelse(Co2_Gas$Country == 'Indonesia',"Asia Pacific",
                                                                                                ifelse(Co2_Gas$Country == 'Japan',"Asia Pacific",
                                                                                                       ifelse(Co2_Gas$Country == 'Malaysia',"Asia Pacific",
                                                                                                              ifelse(Co2_Gas$Country == 'South Korea',"Asia Pacific",
                                                                                                                     ifelse(Co2_Gas$Country == 'Taiwan',"Asia Pacific",
                                                                                                                            ifelse(Co2_Gas$Country == 'Thailand',"Asia Pacific",                                                 
                                                                                                                                   ifelse(Co2_Gas$Country == 'Australia',"Asia Pacific",
                                                                                                                                          ifelse(Co2_Gas$Country == 'New Zealand',"Asia Pacific",
                                                                                                                                                 ifelse(Co2_Gas$Country == 'South Africa',"Middle East and Africa",
                                                                                                                                                        ifelse(Co2_Gas$Country == 'Algeria',"Middle East and Africa",
                                                                                                                                                               ifelse(Co2_Gas$Country == 'Egypt',"Middle East and Africa",
                                                                                                                                                                      ifelse(Co2_Gas$Country == 'Nigeria',"Middle East and Africa",
                                                                                                                                                                             ifelse(Co2_Gas$Country == 'Iran',"Middle East and Africa",
                                                                                                                                                                                    ifelse(Co2_Gas$Country == 'Kuwait',"Middle East and Africa",
                                                                                                                                                                                           ifelse(Co2_Gas$Country == 'Saudi Arabia',"Middle East and Africa", 
                                                                                                                                                                                                  ifelse(Co2_Gas$Country == 'United Arab Emirates',"Middle East and Africa","Europe and CIS"))))))))))))))))))))))))))
Co2_Gas <- Co2_Gas[c(1,4,2,3)]
write.csv(Co2_Gas,file = "Co2_Gas.csv",row.names = FALSE)
Co2_Gas <- Co2_Gas[order(Co2_Gas$Region),]
Co2_Oil <- Co2_Oil[order(Co2_Oil$Region),]
Co2_Oil$Co2_Emission_in_mtCo2 <- format(round(as.numeric(Co2_Oil$Co2_Emission_in_mtCo2), 2), nsmall = 2)
Co2_Gas$Co2_Emission_in_mtCo2 <- format(round(as.numeric(Co2_Gas$Co2_Emission_in_mtCo2), 2), nsmall = 2)
Co2_Gas$Fuel_Type <- rep("Gas",nrow(Co2_Gas))
Co2_Oil$Fuel_Type <- rep("Oil",nrow(Co2_Oil))
Co2_Emission <- rbind(Co2_Gas,Co2_Oil)
Co2_Emission$Region_ID <- as.integer(factor(Co2_Emission$Region))
Co2_Emission$Country_ID <- as.integer(factor(Co2_Emission$Country))
Co2_Emission$Fuel_ID <- as.integer(factor(Co2_Emission$Fuel_Type))
Co2_Emission <- Co2_Emission[c(1,8,5,6,2,7,3,4)]


write.csv(Co2_Emission,file = "Co2_Emission.csv",row.names = FALSE) 
